In [7]:
import numpy as np
from sklearn.datasets import load_iris
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.model_selection import train_test_split

iris = load_iris()
X = iris.data
y = iris.target.reshape(-1, 1)

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

encoder = OneHotEncoder()
y_onehot = encoder.fit_transform(y)

X_train, X_test, y_train, y_test = train_test_split(
    X_scaled, y_onehot, test_size=0.2, random_state=42, stratify=y
)

print(f"Train shape: X={X_train.shape}, y={y_train.shape}")
print(f"Test shape: X={X_test.shape}, y={y_test.shape}")

def relu(z):
    return np.maximum(0, z)

def softmax(z):
    exp_z = np.exp(z - np.max(z, axis=1, keepdims=True))
    return exp_z / np.sum(exp_z, axis=1, keepdims=True)

input_size = 4
hidden_size = 8
output_size = 3

np.random.seed(42)
W1 = np.random.randn(input_size, hidden_size) * 0.1
b1 = np.zeros((1, hidden_size))

W2 = np.random.randn(hidden_size, output_size) * 0.1
b2 = np.zeros((1, output_size))

def forward_pass(X):
    z1 = np.dot(X, W1) + b1
    a1 = relu(z1)

    z2 = np.dot(a1, W2) + b2
    a2 = softmax(z2)

    return a1, a2

hidden_activation, output_probs = forward_pass(X_train)

print("\nExample forward pass outputs:")
print(f"Hidden layer activations (first 5 samples):\n{hidden_activation[:5]}")
print(f"Output probabilities (first 5 samples):\n{output_probs[:5]}")


Train shape: X=(120, 4), y=(120, 3)
Test shape: X=(30, 4), y=(30, 3)

Example forward pass outputs:
Hidden layer activations (first 5 samples):
[[0.13748791 0.         0.17661506 0.         0.         0.17887148
  0.         0.        ]
 [0.         0.         0.         0.         0.0179482  0.2434836
  0.00398705 0.04640616]
 [0.01102419 0.         0.01834997 0.13041466 0.02946146 0.06512068
  0.27334324 0.08681362]
 [0.14737567 0.         0.20450894 0.         0.         0.07915673
  0.         0.        ]
 [0.01842331 0.         0.00476897 0.         0.         0.24823646
  0.14855948 0.04516096]]
Output probabilities (first 5 samples):
[[0.33362598 0.3335644  0.33280963]
 [0.34221793 0.33734292 0.32043915]
 [0.34020589 0.33338557 0.32640853]
 [0.32862394 0.33197697 0.33939909]
 [0.3454107  0.33602456 0.31856475]]
