In [287]:
#   Task 1
import numpy as np
from collections import deque

def BFS(graph, start, end):
    if graph[start[0]][start[1]] != 0:
        print("Start is an Obstacle!")
        return False
    if graph[end[0]][end[1]] != 0:
        print("End is an Obstacle!")
        return False
    
    visited = set()
    queue = deque([(start, [start])])

    rows, cols = np.shape(graph)

    while queue:
        current, path = queue.popleft()

        if current == end:
            return path
        if current in visited:
            continue

        visited.add(current)

        row, col = current

        for i, j in [(0, 1), (0, -1), (1, 0), (-1, 0)]:
            newRow, newCol = row + i, col + j

            if 0 <= newRow < rows and 0 <= newCol < cols and graph[newRow][newCol] == 0:
                queue.append([(newRow, newCol), path + [(newRow, newCol)]])
            
        
    return False

def DFS(graph, start, end):
    if graph[start[0]][start[1]] != 0:
        print("Start is an Obstacle!")
        return False
    if graph[end[0]][end[1]] != 0:
        print("End is an Obstacle!")
        return False
    
    visited = set()
    
    rows, cols = np.shape(graph)

    stack = deque([(start, [start])])

    while stack:
        current, path = stack.pop()

        if current == end:
            return path
        if current in visited:
            continue

        visited.add(current)

        for i, j in [(0, 1), (0, -1), (1, 0), (-1, 0)]:
            newRow, newCol = current[0] + i, current[1] + j

            if 0 <= newRow < rows and 0 <= newCol < cols and graph[newRow][newCol] == 0:
                stack.append([(newRow, newCol), path + [(newRow, newCol)]])
    
    return False


myList = np.ones((10, 10)).astype(int)
myList = (myList + .01 * np.random.randn(10, 10)).astype(int)

print("Graph: \n", myList)

print("\n\nBFS\n")
BFS_path = BFS(myList, (0, 0), (9, 9))

if BFS_path:
    print("Path Found!\nPath: ", BFS_path)
else:
    print("Path Not Found!")


print("\n\nDFS\n")
DFS_path = DFS(myList, (0, 0), (9, 9))

if DFS_path:
    print("Path Found!\nPath: ", DFS_path)
else:
    print("Path Not Found!")

Graph: 
 [[0 0 0 0 0 1 0 0 0 1]
 [1 1 0 1 0 1 1 0 1 1]
 [0 1 1 1 0 1 0 1 1 0]
 [0 0 0 0 0 0 1 0 1 0]
 [0 1 1 0 1 1 0 1 0 0]
 [0 1 0 0 1 1 1 0 0 1]
 [0 1 1 0 0 0 0 0 1 0]
 [1 0 0 1 0 1 1 0 0 0]
 [0 1 1 0 1 0 1 0 1 0]
 [0 1 1 0 0 1 0 0 1 0]]


BFS

Path Found!
Path:  [(0, 0), (0, 1), (0, 2), (0, 3), (0, 4), (1, 4), (2, 4), (3, 4), (3, 3), (4, 3), (5, 3), (6, 3), (6, 4), (6, 5), (6, 6), (6, 7), (7, 7), (7, 8), (7, 9), (8, 9), (9, 9)]


DFS

Path Found!
Path:  [(0, 0), (0, 1), (0, 2), (0, 3), (0, 4), (1, 4), (2, 4), (3, 4), (3, 3), (4, 3), (5, 3), (6, 3), (6, 4), (6, 5), (6, 6), (6, 7), (7, 7), (7, 8), (7, 9), (8, 9), (9, 9)]


In [13]:
#   Task 2
import sys
import random
import numpy as np

def getVals(matrix, i, j):
    return matrix[i][j], matrix[i-1][j], matrix[i+1][j], matrix[i][j-1], matrix[i][j+1]

def getMinima(matrix):
    rows, cols = matrix.shape

    localMinima = []

    for i in range(1, rows - 1):
        for j in range(1, cols - 1):
            curr, up, down, left, right = getVals(matrix, i, j)

            if curr < up and curr < down and curr < left and curr < right:
                localMinima.append([i, j])

    return localMinima

rows = cols = random.randint(1, 10)
myMatrix = [[random.randint(0, 50) for i in range(cols)] for j in range(rows)]

myMatrix = np.array(myMatrix)

for row in myMatrix:
    print(row)

if rows < 3:
    print("No Local Minima")
else:
    localMinima = getMinima(myMatrix)

    if localMinima == []:
        print("No local minima found")
    else:
        for sets in localMinima:
            print(f"Local Minima at ({sets}): {myMatrix[sets[0]][sets[1]]}")

[20 17  0 10 16 25 43 29 50  5]
[25 12  9 28 13  9  8  2 31 14]
[42 28 25 12 27 36 22 39  7 32]
[ 5 37  1 38 46 26 19  5 45 42]
[47 39 49  7 44 32  4 27 27 12]
[38 18 28 27 15 41 16  6 40 14]
[25 16 33  7 18 10 42 37 23  9]
[ 4 40  4 26 11 30 27  7 31 37]
[35  4 42 41 21 10  5 17 12 44]
[22 32  7 15 24  6 48 25 32 19]
Local Minima at ([1, 7]): 2
Local Minima at ([2, 3]): 12
Local Minima at ([2, 8]): 7
Local Minima at ([3, 2]): 1
Local Minima at ([3, 7]): 5
Local Minima at ([4, 3]): 7
Local Minima at ([4, 6]): 4
Local Minima at ([5, 4]): 15
Local Minima at ([5, 7]): 6
Local Minima at ([6, 1]): 16
Local Minima at ([6, 3]): 7
Local Minima at ([6, 5]): 10
Local Minima at ([7, 2]): 4
Local Minima at ([7, 4]): 11
Local Minima at ([7, 7]): 7
Local Minima at ([8, 1]): 4
Local Minima at ([8, 6]): 5
Local Minima at ([8, 8]): 12
